version: '3.8'

services:
  file-manager:
    # 使用GitHub Container Registry的预构建镜像
    image: ghcr.io/jianjunx/file-manager:latest
    ports:
      - "8000:8000"
    volumes:
      # 将主机目录映射到容器的/data目录
      - ./data:/data
      # 如果需要管理其他目录，可以修改这里
      # - /path/to/your/files:/data
    environment:
      - PORT=8000
      # 身份验证配置 - 如果设置了用户名和密码，则启用身份验证
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=your_secure_password
      # 可选：Session密钥
      # - SESSION_SECRET=your_random_secret_key
    restart: unless-stopped
    container_name: file-manager-ghcr
    
  # 可选：如果需要反向代理
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - file-manager
  #   restart: unless-stopped 