version: '3.8'

services:
  file-manager:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # 将主机目录映射到容器的/data目录
      - ./data:/data
      # 如果需要管理其他目录，可以修改这里
      # - /path/to/your/files:/data
    environment:
      - PORT=8000
    restart: unless-stopped
    container_name: file-manager
    
  # 可选：如果需要反向代理
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - file-manager
  #   restart: unless-stopped 